Document: capture
Title: Debian capture Manual
Author: <insert document author here>
Abstract: This manual describes what capture is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/capture/capture.sgml.gz

Format: postscript
Files: /usr/share/doc/capture/capture.ps.gz

Format: text
Files: /usr/share/doc/capture/capture.text.gz

Format: HTML
Index: /usr/share/doc/capture/html/index.html
Files: /usr/share/doc/capture/html/*.html
