Document: oedd
Title: Debian oedd Manual
Author: <insert document author here>
Abstract: This manual describes what oedd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/oedd/oedd.sgml.gz

Format: postscript
Files: /usr/share/doc/oedd/oedd.ps.gz

Format: text
Files: /usr/share/doc/oedd/oedd.text.gz

Format: HTML
Index: /usr/share/doc/oedd/html/index.html
Files: /usr/share/doc/oedd/html/*.html
